# Generated by Django 3.0.7 on 2020-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('provider', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
